apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData:
  mongodb-username: {{ .Values.mongodb.username | quote }}
  mongodb-password: {{ .Values.mongodb.password | quote }}
  mongodb-uri: {{ .Values.mongodb.uri | quote }}
  mongodb-database: {{ .Values.mongodb.database | quote }}
  mongodb-collection: {{ .Values.mongodb.collection | quote }}
