apiVersion: v1
kind: Service
metadata:
  name: receipt-backend-service
  labels:
    app: receipt-backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: receipt-backend
