apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-backend
  labels:
    app: receipt-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receipt-backend
  template:
    metadata:
      labels:
        app: receipt-backend
    spec:
      containers:
      - name: receipt-backend
        image: venkatakurathitud/receipt-backend:latest
        ports:
        - containerPort: 9090
        env:
        - name: SPRING_DATA_MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-uri
        - name: SPRING_DATA_MONGODB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-database
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9090
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
