apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      initContainers:
      - name: init-mongo
        image: mongo:latest
        command:
          - bash
          - -c
          - |
            set -e
            echo "Starting mongod..."
            mkdir -p /data/db
            mongod --dbpath /data/db --fork --logpath /tmp/mongod.log
            echo "Waiting for mongod to be ready..."
            for i in {1..30}; do
              if mongosh --quiet --eval "db.runCommand({ ping: 1 })" >/dev/null 2>&1; then
                echo "mongod is ready"
                break
              fi
              sleep 2
              if [ $i -eq 30 ]; then
                echo "mongod failed to start"
                exit 1
              fi
            done
            echo "Creating admin user..."
            mongosh admin --eval "db.createUser({ user: '$MONGO_INITDB_ROOT_USERNAME', pwd: '$MONGO_INITDB_ROOT_PASSWORD', roles: [{ role: 'root', db: 'admin' }] })"
            echo "Shutting down mongod..."
            mongosh admin --eval "db.shutdownServer()" || true
            echo "Init complete"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-password
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      containers:
      - name: mongodb
        image: mongo:latest
        command: ["mongod", "--wiredTigerCacheSizeGB=0.25", "--bind_ip_all", "--auth"]
        ports:
        - containerPort: 27017
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-database
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP