apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # These are base64 encoded placeholders - replace with actual values
  # To encode: echo -n "your-value" | base64
  mongodb-uri: base64EncodedMongoDBUri
  mongodb-database: base64EncodedMongoDBDatabase 