namespace: dev
replicaCount: 2

image:
  repository: docker.io/venkatakurathitud/receipt-backend
  tag: latest
  pullPolicy: Always

mongodb:
  username: ""
  password: ""
  uri: ""
  database: ""
  collection: ""

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"

javaOpts: "-Dlogging.level.org.springframework.data.mongodb=DEBUG -Dlogging.level.org.mongodb.driver=DEBUG"

service:
  type: ClusterIP
  port: 80
  targetPort: 9090
