apiVersion: apps/v1
kind: Deployment
metadata:
  name: receipt-backend
  labels:
    app: receipt-backend
spec:
  replicas: 2
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      app: receipt-backend
  template:
    metadata:
      labels:
        app: receipt-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/actuator/prometheus"
        sidecar.istio.io/inject: "false"
    spec:
      volumes:
      - name: tmp-volume
        emptyDir: {} # Define an emptyDir volume named 'tmp-volume'

      containers:
      - name: receipt-backend
        image: docker.io/venkatakurathitud/receipt-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-uri
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-database
        - name: MONGO_COLLECTION
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-collection
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-username
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-password
        - name: JAVA_OPTS
          value: "-Dlogging.level.org.springframework.data.mongodb=DEBUG -Dlogging.level.org.mongodb.driver=DEBUG"
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 9090
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 5