apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - mongodb-deployment.yaml
  - mongodb-pvc.yaml
images:
  - name: docker.io/venkatakurathitud/receipt-backend
    newTag: SHORT_SHA