apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
stringData: {}

  # mongodb-username: placeholder-username
  # mongodb-password: placeholder-password
  # mongodb-uri: placeholder-uri
  # mongodb-database: placeholder-database
  # mongodb-collection: placeholder-collection