apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: receipt-backend-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: receipt-backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mongodb-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: mongodb 