apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../base
patchesStrategicMerge:
- patch-mongodb-pvc-storageclass.yaml # Include the patch file
images:
- name: docker.io/venkatakurathitud/receipt-backend
  newName: docker.io/venkatakurathitud/receipt-backend
  newTag: ${SHORT_SHA}