apiVersion: v1
kind: Service
metadata:
  name: receipt-backend-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/actuator/prometheus"
spec:
  ports:
    - name: metrics
      port: 9090
      targetPort: 9090 